Repository colindamelio/saraswati, pull requests merged in 2018-09, with the labels that each got.

#7 feat(LandingPage): Creating components + initial styling
  src/components/Body.js
  src/components/BodyText.js
  src/components/Button.js
  src/components/H1.js
  src/components/H2.js
  src/components/HeroWithContent.js
  src/components/Image.js
  src/components/LandingModule.js
  src/routes/Home.js
  src/utils/mq.js
Labels: ready for review

#9 Preliminary Refactoring
  public/index.html
  src/components/Application.js
  src/components/ApplicationForm.js
  src/components/BodyText.js
  src/components/BodyTextLockup.js
  src/components/Bold.js
  src/components/Button.js
  src/components/Experience.js
  src/components/Footer.js
  src/components/H1.js
  src/components/H2.js
  src/components/Hero.js
  src/components/Information.js
  src/components/LandingModule.js
  src/components/Link.js
  src/components/LinkButton.js
  src/components/Navigation.js
  src/components/Overview.js
  src/components/SplitHero.js
  src/components/Tout.js
  src/index.css
  src/routes/Home.js
  src/theme/index.js
Labels: work in progress

#11 feat(resourceStrings): Strings object
  src/App.js
  src/components/Body.js
  src/components/LandingModule.js
  src/data/culture.js
  src/data/curriculum.js
  src/data/form.js
  src/data/landing.js
  src/data/resource-strings.js
  src/routes/Home.js
Labels: ready for review

#18 fix: Fine-tuning of our CSS
  src/components/BodyTextLockup.js
  src/components/Button.js
  src/components/Form.js
  src/components/H1.js
  src/components/Hero.js
  src/components/SplitHero.js
  src/modules/Header.js
  src/modules/Join.js
  src/modules/PageContent.js
  src/modules/culture/CultureInformation.js
  src/modules/culture/CultureIntro.js
  src/modules/culture/Experience.js
  src/modules/curriculum/CurriculumInformation.js
  src/modules/curriculum/CurriculumIntro.js
  src/modules/curriculum/LearningEnvironment.js
  src/modules/home/Accommodations.js
  src/modules/home/CurriculumOverview.js
  src/modules/home/LandingIntro.js
  src/modules/home/RetreatInformation.js
  src/routes/Culture.js
  src/routes/Curriculum.js
  src/routes/Home.js
  src/theme/index.js
Labels: ready for review

#42 Update CTA text and new landing section
  src/modules/Join.js
  src/modules/culture/Experience.js
  src/modules/home/Application.js
  src/modules/home/CulturalOverview.js
  src/modules/home/CultureOnly.js
  src/modules/home/CurriculumOverview.js
  src/modules/home/LandingIntro.js
  src/routes/Home.js
Labels: enhancement, ready for review
